# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: ds
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
      POSTGRES_DB: ${POSTGRES_DB:?error} 
      POSTGRES_USER: ${POSTGRES_USER:?error}

  pg-admin:
    container_name: pg
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:8080
    environment:
      - PGADMIN_LISTEN_PORT=8080

# docker compose up
# docker exec -it ds psql -U znichola